### PR TITLE
cln: support the new model change inside the v0.22.+, and include a new test framework written in rust

### PR DESCRIPTION
**Pull request by evd0kim**
It was discovered that v0.22 has different `listpeers` output. So this little PR should fix situation.

### CODE REVIEW

**Comment by vincenzopalazzo** [comment]
yeah, we need to upgrade the API. 

but I think the list of peers in this API is not touched. also, can you remove the merge commit and add a `fix(rpc):` in front of your commit header?

**Comment by evd0kim** [comment]
@vincenzopalazzo is it really important if you do squashing eventually?

**Comment by vincenzopalazzo** [comment]
>@vincenzopalazzo is it really important if you do squashing eventually?

Yes because I will generate the changelog from it

**Comment by vincenzopalazzo** [comment]
Ok in there it is missing the following steps:

- Fix the CI (I think it is just a lint warning)
- squash the commit in a single one with the following commit header `fix(rpc): fix rpc model in according with cln v22.11.1`

**Review by vincenzopalazzo — CHANGES_REQUESTED** [review]
Ok looks like that the following warning and error are left before merging them

Warning

```
rust_clightning_rpc_1  | warning: unused import: `clightningrpc::lightningrpc::PayOptions`
rust_clightning_rpc_1  |  --> rpc/tests/cln_regtest.rs:3:5
rust_clightning_rpc_1  |   |
rust_clightning_rpc_1  | 3 | use clightningrpc::lightningrpc::PayOptions;
rust_clightning_rpc_1  |   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rust_clightning_rpc_1  |   |
rust_clightning_rpc_1  |   = note: `#[warn(unused_imports)]` on by default
rust_clightning_rpc_1  | 
rust_clightning_rpc_1  | warning: unused import: `p256::elliptic_curve::weierstrass::add`
rust_clightning_rpc_1  |  --> rpc/tests/cln_regtest.rs:6:5
rust_clightning_rpc_1  |   |
rust_clightning_rpc_1  | 6 | use p256::elliptic_curve::weierstrass::add;
rust_clightning_rpc_1  |   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rust_clightning_rpc_1  | 
rust_clightning_rpc_1  | warning: unused import: `cln_btc_test::runner::*`
rust_clightning_rpc_1  |  --> rpc/tests/cln_regtest.rs:9:5
rust_clightning_rpc_1  |   |
rust_clightning_rpc_1  | 9 | use cln_btc_test::runner::*;
rust_clightning_rpc_1  |   |     ^^^^^^^^^^^^^^^^^^^^^^^
rust_clightning_rpc_1  | 
rust_clightning_rpc_1  | warning: `clightningrpc` (test "cln_regtest") generated 3 **warnings**
```

Errors 

```
rust_clightning_rpc_1  | error[E0061]: this function takes 5 arguments but 4 arguments were supplied
rust_clightning_rpc_1  |    --> rpc/tests/rpc_utility_test.rs:100:10
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 100 |         .invoice(None, label.as_str(), "generate an any invoice", None)
rust_clightning_rpc_1  |     |          ^^^^^^^------------------------------------------------------- an argument of type `Option<u64>` is missing
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | note: associated function defined here
rust_clightning_rpc_1  |    --> /workdir/code/rpc/src/lightningrpc.rs:149:12
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 149 |     pub fn invoice(
rust_clightning_rpc_1  |     |            ^^^^^^^
rust_clightning_rpc_1  | help: provide the argument
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 100 |         .invoice(None, label.as_str(), "generate an any invoice", None, /* Option<u64> */)
rust_clightning_rpc_1  |     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust_clightning_rpc_1  | 
rust_clightning_rpc_1  | error[E0061]: this function takes 5 arguments but 4 arguments were supplied
rust_clightning_rpc_1  |    --> rpc/tests/rpc_utility_test.rs:110:10
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 110 |         .invoice(Some(1), label.as_str(), "generate an any invoice", None)
rust_clightning_rpc_1  |     |          ^^^^^^^---------------------------------------------------------- an argument of type `Option<u64>` is missing
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | note: associated function defined here
rust_clightning_rpc_1  |    --> /workdir/code/rpc/src/lightningrpc.rs:149:12
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 149 |     pub fn invoice(
rust_clightning_rpc_1  |     |            ^^^^^^^
rust_clightning_rpc_1  | help: provide the argument
rust_clightning_rpc_1  |     |
rust_clightning_rpc_1  | 110 |         .invoice(Some(1), label.as_str(), "generate an any invoice", None, /* Option<u64> */)
rust_clightning_rpc_1  |     |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
rust_clightning_rpc_1  | 
rust_clightning_rpc_1  | For more information about this error, try `rustc --explain E0061`.
rust_clightning_rpc_1  | error: could not compile `clightningrpc` due to 2 previous errors
rust_clightning_rpc_1  | warning: build failed, waiting for other jobs to finish...
cln4rust_rust_clightning_rpc_1 exited with code 101
```

I think I will use your test framework inside the CI and rewrite the integration testing!

Thanks for all this job!

**Comment by evd0kim** [comment]
@vincenzopalazzo yes. It is not clean and I should close this PR before pushing.

**Comment by vincenzopalazzo** [comment]
If you are not planning to get this as PR, I would like to rework your commits and push it as a package if you agree!

**Comment by evd0kim** [comment]
@vincenzopalazzo sure. Lets do it on the way you see the most fitting.

**Pull request closed without merging**
